run dump
I ran the script and now I get the following errors. Please review and fix these errors
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/RebuildCommand.cs(19,46): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/RebuildCommand.cs(19,46): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/RebuildCommand.cs(19,46): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/RebuildCommand.cs(19,47): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/RebuildCommand.cs(19,56): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(25,43): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(25,43): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(25,43): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(25,44): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(25,55): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(31,47): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(31,47): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(31,47): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(31,48): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Commands/SearchCommand.cs(31,60): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(23,49): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(23,49): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(23,49): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(23,50): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(23,63): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(28,46): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(28,46): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(28,46): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(28,47): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(28,60): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(33,50): error CS1729: 'string' does not contain a constructor that takes 0 arguments
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(33,50): error CS9215: Collection expression type 'string' must have an instance or extension method 'Add' that can be called with a single argument.
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(33,50): error CS1929: 'string' does not contain a definition for 'Add' and the best extension method overload 'CompletionSourceExtensions.Add(List<Func<CompletionContext, IEnumerable<CompletionItem>>>, Func<CompletionContext, IEnumerable<string>>)' requires a receiver of type 'System.Collections.Generic.List<System.Func<System.CommandLine.Completions.CompletionContext, System.Collections.Generic.IEnumerable<System.CommandLine.Completions.CompletionItem>>>'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(33,51): error CS0029: Cannot implicitly convert type 'string' to 'char'
/home/kushal/src/dotnet/MyImapDownloader/MyEmailSearch/Program.cs(33,65): error CS0029: Cannot implicitly convert type 'string' to 'char'
Get projects properties with MSBuild didn't execute properly with exit code: 1.